export interface Product {
  id: string;
  slug: string;
  name: string;
  category: "hair" | "nails" | "accessories" | "beauty"; // Correction: Added beauty
  subcategory: string;
  price: number;
  originalPrice?: number;
  images: string[];
  rating: number;
  reviewCount: number;
  inStock: boolean;
  stockCount: number;
  tags: string[];
  description: string;
  details: string[];
  isNew: boolean;
  isBestseller: boolean;
  isSale: boolean;
  careInstructions?: string;
  shadeOptions?: string[];
  lengthOptions?: string[];
}

export const products: Product[] = [
  // --- HAIR PRODUCTS (12 items) ---
  {
    id: "prod-h1",
    slug: "brazilian-straight-hair-18",
    name: 'Brazilian Straight Hair Bundle (18")',
    category: "hair",
    subcategory: "Bundles",
    price: 45000,
    images: ["https://images.unsplash.com/photo-1595475242261-067c14b036c3"],
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    stockCount: 15,
    tags: ["human hair", "brazilian", "straight"],
    description:
      "Premium grade human hair with a natural shine and silky texture.",
    details: ["100% Virgin Hair", "No shedding", "Can be dyed and bleached"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    lengthOptions: ["18", "20", "22", "24"],
  },
  {
    id: "prod-h2",
    slug: "kinky-curly-closure-4x4",
    name: "Kinky Curly Closure 4x4",
    category: "hair",
    subcategory: "Closures",
    price: 28500,
    images: ["https://images.unsplash.com/photo-1634449571010-02389ed0f9b0"],
    rating: 4.7,
    reviewCount: 45,
    inStock: true,
    stockCount: 10,
    tags: ["kinky curly", "closure", "lace"],
    description: "High-quality 4x4 lace closure with natural curly patterns.",
    details: ["Swiss Lace", "Pre-plucked hairline", "Natural black color"],
    isNew: true,
    isBestseller: true,
    isSale: true,
    lengthOptions: ["20", "22", "24", "26"],
  },
  {
    id: "prod-h3",
    slug: "hd-lace-frontal-13x4",
    name: "HD Lace Frontal 13x4",
    category: "hair",
    subcategory: "Frontals",
    price: 62000,
    images: ["https://images.unsplash.com/photo-1565121345959-10e6e960b730"],
    rating: 4.9,
    reviewCount: 32,
    inStock: true,
    stockCount: 5,
    tags: ["HD lace", "frontal", "luxury"],
    description: "Ultra-thin HD lace that melts perfectly into any skin tone.",
    details: ["13x4 Coverage", "Invisible knots", "High definition lace"],
    isNew: true,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "prod-h4",
    slug: "deep-wave-full-lace-wig",
    name: "Deep Wave Full Lace Wig",
    category: "hair",
    subcategory: "Wigs",
    price: 95000,
    images: ["https://images.unsplash.com/photo-1605497746465-95394e48ef94"],
    rating: 4.8,
    reviewCount: 18,
    inStock: true,
    stockCount: 3,
    tags: ["deep wave", "full lace", "wig"],
    description: "Full lace construction for maximum styling versatility.",
    details: ["180% Density", "Adjustable straps", "Can be worn glueless"],
    isNew: false,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "prod-h5",
    slug: "bone-straight-bundle-20",
    name: 'Bone Straight Hair Bundle (20")',
    category: "hair",
    subcategory: "Bundles",
    price: 52000,
    images: ["https://images.unsplash.com/photo-1574621100236-d25b64cfd647"],
    rating: 5.0,
    reviewCount: 210,
    inStock: true,
    stockCount: 25,
    tags: ["bone straight", "bundle", "vietnamese"],
    description: "Super double drawn bone straight hair that stays sleek.",
    details: [
      "Vietnamese origin",
      "Steam processed",
      "Stays straight after wash",
    ],
    isNew: false,
    isBestseller: true,
    isSale: false,
    lengthOptions: ["20", "22", "24", "26"],
  },
  {
    id: "prod-h6",
    slug: "jerry-curl-weave-bundle",
    name: "Jerry Curl Weave Bundle",
    category: "hair",
    subcategory: "Bundles",
    price: 38000,
    images: ["https://images.unsplash.com/photo-1492106087820-71f1a00d2b11"],
    rating: 4.4,
    reviewCount: 56,
    inStock: true,
    stockCount: 12,
    tags: ["jerry curl", "weave", "bouncy"],
    description: "Bouncy, soft curls that maintain their pattern for months.",
    details: ["Soft texture", "Low maintenance", "Minimum tangling"],
    isNew: false,
    isBestseller: false,
    isSale: true,
    originalPrice: 42000,
  },
  {
    id: "prod-h7",
    slug: "raw-indian-hair-extension",
    name: "Raw Indian Hair Extension",
    category: "hair",
    subcategory: "Luxury",
    price: 41000,
    images: ["https://images.unsplash.com/photo-1596178065887-1198b6148b2b"],
    rating: 4.9,
    reviewCount: 22,
    inStock: true,
    stockCount: 7,
    tags: ["raw indian", "unprocessed"],
    description: "Single donor raw hair from Indian temples. Purest quality.",
    details: ["Coarse texture", "Lasts 3-5 years", "Completely unprocessed"],
    isNew: true,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "prod-h8",
    slug: "silk-press-heat-protectant",
    name: "Silk Press Heat Protectant",
    category: "hair",
    subcategory: "Care",
    price: 8500,
    images: ["https://images.unsplash.com/photo-1526947425960-945c6e72858f"],
    rating: 4.8,
    reviewCount: 150,
    inStock: true,
    stockCount: 45,
    tags: ["silk press", "heat protectant", "care"],
    description: "Protects hair from thermal damage during straightening.",
    details: ["Up to 450°F protection", "Lightweight formula", "Adds shine"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "prod-h9",
    slug: "curl-defining-cream",
    name: "Curl Defining Cream",
    category: "hair",
    subcategory: "Care",
    price: 6200,
    images: ["https://images.unsplash.com/photo-1552046122-03184de85e08"],
    rating: 4.6,
    reviewCount: 94,
    inStock: true,
    stockCount: 30,
    tags: ["curls", "styling", "natural hair"],
    description: "Enhances and defines natural curls without the crunch.",
    details: ["Anti-frizz", "Moisture locking", "Paraben-free"],
    isNew: false,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "prod-h10",
    slug: "deep-conditioning-mask",
    name: "Deep Conditioning Mask",
    category: "hair",
    subcategory: "Care",
    price: 7800,
    images: ["https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d"],
    rating: 4.7,
    reviewCount: 112,
    inStock: true,
    stockCount: 20,
    tags: ["conditioning", "repair", "hair mask"],
    description: "Intensive treatment to repair damaged and dry hair.",
    details: ["Keratin enriched", "Deep hydration", "Use once weekly"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "prod-h11",
    slug: "scalp-serum-growth",
    name: "Scalp Serum (Growth Formula)",
    category: "hair",
    subcategory: "Care",
    price: 12500,
    images: ["https://images.unsplash.com/photo-1608248597279-f99d160bfcbc"],
    rating: 4.9,
    reviewCount: 67,
    inStock: true,
    stockCount: 15,
    tags: ["growth", "scalp", "serum"],
    description: "Stimulates follicles for healthy, rapid hair growth.",
    details: ["Biotin & Peppermint", "Non-greasy", "Daily use"],
    isNew: true,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "prod-h12",
    slug: "satin-lined-bonnet",
    name: "Satin-Lined Bonnet (Luxury)",
    category: "hair",
    subcategory: "Accessories",
    price: 4500,
    images: ["https://images.unsplash.com/photo-1632345031435-8727f6897d53"],
    rating: 5.0,
    reviewCount: 300,
    inStock: true,
    stockCount: 50,
    tags: ["bonnet", "satin", "night care"],
    description: "Extra large luxury bonnet to protect styles during sleep.",
    details: ["Double layered", "Adjustable band", "Prevents frizz"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },

  // --- NAIL PRODUCTS (10 items) ---
  {
    id: "prod-n1",
    slug: "gel-nail-kit-complete",
    name: "Gel Nail Kit (Complete Set)",
    category: "nails",
    subcategory: "Kits",
    price: 22000,
    images: ["https://images.unsplash.com/photo-1604654894610-df490c9397ae"],
    rating: 4.5,
    reviewCount: 45,
    inStock: true,
    stockCount: 10,
    tags: ["gel", "nail kit", "DIY"],
    description: "All-in-one kit for salon-quality nails at home.",
    details: ["36W UV Lamp", "6 Gel colors", "Base/Top coat"],
    isNew: true,
    isBestseller: false,
    isSale: true,
    originalPrice: 25000,
  },
  {
    id: "prod-n2",
    slug: "press-on-nails-french",
    name: "Press-On Nails — French Tips (24pc)",
    category: "nails",
    subcategory: "Press-Ons",
    price: 5500,
    images: ["https://images.unsplash.com/photo-1607613009820-a29f7bb81c04"],
    rating: 4.3,
    reviewCount: 120,
    inStock: true,
    stockCount: 35,
    tags: ["french tip", "press-on", "classic"],
    description: "Classic elegant French tips for instant manicures.",
    details: ["Glue included", "Reusable", "Shapeable"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    lengthOptions: ["Short", "Medium", "Long"],
  },
  {
    id: "prod-n3",
    slug: "press-on-nails-nude",
    name: "Press-On Nails — Nude Ombre (24pc)",
    category: "nails",
    subcategory: "Press-Ons",
    price: 5500,
    images: ["https://images.unsplash.com/photo-1519014816548-bf5fe059798b"],
    rating: 4.4,
    reviewCount: 88,
    inStock: true,
    stockCount: 20,
    tags: ["nude", "ombre", "press-on"],
    description: "Trendy nude ombre fade for a modern aesthetic.",
    details: ["Natural finish", "Long length", "High gloss"],
    isNew: true,
    isBestseller: false,
    isSale: false,
    shadeOptions: ["Stiletto Shape", "Square Shape", "Coffin Shape"],
  },
  {
    id: "prod-n4",
    slug: "press-on-nails-floral",
    name: "Press-On Nails — Floral Art (24pc)",
    category: "nails",
    subcategory: "Press-Ons",
    price: 6500,
    images: ["https://images.unsplash.com/photo-1632345031435-8727f6897d53"],
    rating: 4.8,
    reviewCount: 54,
    inStock: true,
    stockCount: 15,
    tags: ["floral", "art", "press-on"],
    description: "Hand-painted floral designs on premium press-on nails.",
    details: ["Limited edition", "Stiletto shape", "Strong adhesive"],
    isNew: true,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "prod-n5",
    slug: "nail-lamp-uv-led",
    name: "Nail Lamp UV/LED (36W)",
    category: "nails",
    subcategory: "Equipment",
    price: 18500,
    images: ["https://images.unsplash.com/photo-1627383200760-4740e53a299d"],
    rating: 4.7,
    reviewCount: 39,
    inStock: true,
    stockCount: 8,
    tags: ["nail lamp", "UV", "LED"],
    description: "Powerful curing lamp with smart sensor technology.",
    details: ["3 Timer modes", "Painless mode", "Removable base"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "prod-n6",
    slug: "gel-polish-collection-12",
    name: "Gel Polish Collection (12 colours)",
    category: "nails",
    subcategory: "Polishes",
    price: 15000,
    images: ["https://images.unsplash.com/photo-1599733594230-6b823276abcc"],
    rating: 4.9,
    reviewCount: 72,
    inStock: true,
    stockCount: 14,
    tags: ["gel polish", "color set", "glitter"],
    description: "A curation of seasonal favorite gel polish shades.",
    details: ["No-chip formula", "Vibrant pigments", "Lasts 4 weeks"],
    isNew: true,
    isBestseller: true,
    isSale: false,
    shadeOptions: ["Pastel", "Neon", "Corporate"],
  },
  {
    id: "prod-n7",
    slug: "nail-drill-machine-pro",
    name: "Nail Drill Machine (Pro)",
    category: "nails",
    subcategory: "Equipment",
    price: 32000,
    images: ["https://images.unsplash.com/photo-1522338242992-e1a54906a8da"],
    rating: 4.6,
    reviewCount: 25,
    inStock: true,
    stockCount: 5,
    tags: ["nail drill", "professional", "electric"],
    description: "High-speed electric nail file for removals and prep.",
    details: ["35000 RPM", "Quiet motor", "Includes 6 drill bits"],
    isNew: false,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "prod-n8",
    slug: "cuticle-oil-serum",
    name: "Cuticle Oil Serum",
    category: "nails",
    subcategory: "Care",
    price: 3800,
    images: ["https://images.unsplash.com/photo-1610991140635-be00185e3472"],
    rating: 4.9,
    reviewCount: 156,
    inStock: true,
    stockCount: 40,
    tags: ["cuticle oil", "care", "nourishing"],
    description: "Infused with Jojoba and Vitamin E to repair cuticles.",
    details: ["Travel friendly", "Pen applicator", "Fast absorbing"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "prod-n9",
    slug: "nail-art-brush-set",
    name: "Nail Art Brush Set (12pc)",
    category: "nails",
    subcategory: "Tools",
    price: 7200,
    images: ["https://images.unsplash.com/photo-1610991140660-8f6452286e92"],
    rating: 4.2,
    reviewCount: 41,
    inStock: true,
    stockCount: 18,
    tags: ["brushes", "nail art", "tools"],
    description: "Complete set of brushes for liners, flowers, and dots.",
    details: ["Fine bristles", "Wooden handles", "Easy to clean"],
    isNew: false,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "prod-n10",
    slug: "acrylic-powder-kit",
    name: "Acrylic Powder Kit",
    category: "nails",
    subcategory: "Acrylics",
    price: 19500,
    images: ["https://images.unsplash.com/photo-1610991140685-6b6452286e92"],
    rating: 4.5,
    reviewCount: 30,
    inStock: true,
    stockCount: 12,
    tags: ["acrylic", "nail kit", "builder"],
    description: "Pro-quality acrylic powder and monomer set.",
    details: ["Non-yellowing", "Clear & Nude", "Strong bond"],
    isNew: false,
    isBestseller: false,
    isSale: false,
  },

  // --- BEAUTY ACCESSORIES (10 items) ---
  {
    id: "prod-a1",
    slug: "silk-pillowcase-queen",
    name: "Silk Pillowcase (Queen Size)",
    category: "accessories",
    subcategory: "Sleep",
    price: 9500,
    images: ["https://images.unsplash.com/photo-1584100936595-c0654b55a2e2"],
    rating: 4.9,
    reviewCount: 124,
    inStock: true,
    stockCount: 40,
    tags: ["silk", "sleep", "care"],
    description: "Luxurious mulberry silk to protect hair from friction.",
    details: ["100% Silk", "Queen size", "Zip closure"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "prod-a2",
    slug: "jade-roller-set",
    name: "Jade Roller & Gua Sha Set",
    category: "accessories",
    subcategory: "Skincare Tools",
    price: 12000,
    images: ["https://images.unsplash.com/photo-1588775017539-7561845112be"],
    rating: 4.7,
    reviewCount: 65,
    inStock: true,
    stockCount: 22,
    tags: ["skincare", "jade roller", "gua sha"],
    description: "Natural jade stone tools for facial massage and drainage.",
    details: ["Real jade", "Cooling effect", "Includes pouch"],
    isNew: true,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "prod-a3",
    slug: "vanity-mirror-lights",
    name: "Vanity Mirror with Lights",
    category: "accessories",
    subcategory: "Furniture",
    price: 35000,
    images: ["https://images.unsplash.com/photo-1512496015851-a90fb38ba796"],
    rating: 4.8,
    reviewCount: 42,
    inStock: true,
    stockCount: 6,
    tags: ["mirror", "LED", "vanity"],
    description: "Hollywood style mirror with adjustable LED brightness.",
    details: ["3 Light modes", "Touch control", "USB charging"],
    isNew: true,
    isBestseller: true,
    isSale: false,
    shadeOptions: ["Rose Gold", "Classic White", "Sleet Black"],
  },
  {
    id: "prod-a4",
    slug: "makeup-brush-set-24",
    name: "Makeup Brush Set (24pc)",
    category: "accessories",
    subcategory: "Makeup Tools",
    price: 18000,
    images: ["https://images.unsplash.com/photo-1522338140262-f46f5913618a"],
    rating: 4.6,
    reviewCount: 110,
    inStock: true,
    stockCount: 15,
    tags: ["makeup", "brushes", "glam"],
    description: "Comprehensive set for face, eyes, and lips.",
    details: ["Synthetic hair", "Leather roll case", "Professional grade"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "prod-a5",
    slug: "perfume-atomiser-gold",
    name: "Perfume Atomiser (Gold)",
    category: "accessories",
    subcategory: "Travel",
    price: 4200,
    images: ["https://images.unsplash.com/photo-1547881338-64645ed0c1ca"],
    rating: 4.5,
    reviewCount: 95,
    inStock: true,
    stockCount: 50,
    tags: ["travel", "perfume", "gold"],
    description: "Refillable travel bottle for your favorite scents.",
    details: ["5ml Capacity", "Leak proof", "Metallic finish"],
    isNew: false,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "prod-a6",
    slug: "eyelash-extension-kit",
    name: "Eyelash Extension Kit",
    category: "accessories",
    subcategory: "Lashes",
    price: 14500,
    images: ["https://images.unsplash.com/photo-1512496015851-a90fb38ba796"],
    rating: 4.4,
    reviewCount: 28,
    inStock: true,
    stockCount: 12,
    tags: ["lashes", "kit", "professional"],
    description: "Starter kit for individual lash extensions.",
    details: ["Glue included", "Various lengths", "Tweezers included"],
    isNew: false,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "prod-a7",
    slug: "hair-steamer-tabletop",
    name: "Hair Steamer (Tabletop)",
    category: "accessories",
    subcategory: "Equipment",
    price: 55000,
    images: ["https://images.unsplash.com/photo-1522338140262-f46f5913618a"],
    rating: 4.9,
    reviewCount: 15,
    inStock: true,
    stockCount: 4,
    tags: ["steamer", "hydration", "salon at home"],
    description: "Professional grade steamer for deep hydration.",
    details: ["Ionic technology", "Compact design", "Safety shutoff"],
    isNew: true,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "prod-a8",
    slug: "detangling-shower-brush",
    name: "Detangling Shower Brush",
    category: "accessories",
    subcategory: "Hair Tools",
    price: 3500,
    images: ["https://images.unsplash.com/photo-1590159202367-6745d19d6796"],
    rating: 4.7,
    reviewCount: 180,
    inStock: true,
    stockCount: 45,
    tags: ["brush", "detangle", "shower"],
    description: "Painless detangling on wet or dry hair.",
    details: ["Soft bristles", "Ergonomic grip", "Durable material"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "prod-a9",
    slug: "satin-hair-scrunchie-set",
    name: "Satin Hair Scrunchie Set (6pc)",
    category: "accessories",
    subcategory: "Hair Tools",
    price: 2800,
    images: ["https://images.unsplash.com/photo-1594913217409-906f36f86c87"],
    rating: 5.0,
    reviewCount: 142,
    inStock: true,
    stockCount: 60,
    tags: ["scrunchie", "satin", "colors"],
    description: "Gentle hair ties that don't leave creases.",
    details: ["Premium satin", "Elastic stretch", "Multi-colored"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    shadeOptions: ["Pastels", "Jewel Tones", "Neutral Nudes"],
  },
  {
    id: "prod-a10",
    slug: "magnetic-lashes-3",
    name: "Magnetic Lashes (3 pairs)",
    category: "accessories",
    subcategory: "Lashes",
    price: 8000,
    images: ["https://images.unsplash.com/photo-1583001838975-d546a1631911"],
    rating: 4.1,
    reviewCount: 50,
    inStock: true,
    stockCount: 20,
    tags: ["magnetic", "lashes", "reusable"],
    description: "Easy apply magnetic lashes with liquid liner.",
    details: ["No glue", "Wind proof", "Includes applicator"],
    isNew: false,
    isBestseller: false,
    isSale: false,
  },

  // --- 15 BOOKABLE SERVICES ---
  {
    id: "serv-1",
    slug: "luxury-silk-press",
    name: "Luxury Silk Press",
    category: "hair",
    subcategory: "Services",
    price: 15000,
    images: ["https://images.unsplash.com/photo-1560869713-7d0a294308ed"],
    rating: 5.0,
    reviewCount: 88,
    inStock: true,
    stockCount: 99,
    tags: ["popular", "silk press"],
    description: "Our signature silk press includes detox wash and steam.",
    details: ["2 hours", "Includes trim", "Deep conditioning"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "serv-2",
    slug: "knotless-braids",
    name: "Knotless Braids (Medium)",
    category: "hair",
    subcategory: "Services",
    price: 35000,
    images: ["https://images.unsplash.com/photo-1649931440407-744030615276"],
    rating: 4.9,
    reviewCount: 52,
    inStock: true,
    stockCount: 99,
    tags: ["braids", "protective"],
    description: "Painless, lightweight braids. Extensions included.",
    details: ["6 hours", "Hair included", "Mid-back length"],
    isNew: true,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "serv-3",
    slug: "wig-install",
    name: "Frontal Wig Install",
    category: "hair",
    subcategory: "Services",
    price: 25000,
    images: ["https://images.unsplash.com/photo-1634449571010-02389ed0f9b0"],
    rating: 4.8,
    reviewCount: 41,
    inStock: true,
    stockCount: 99,
    tags: ["frontal", "install"],
    description: "Lace melting and customization for a natural look.",
    details: ["3 hours", "Includes styling", "Glue-less available"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "serv-4",
    slug: "bridal-updo",
    name: "Bridal Hair Updo",
    category: "hair",
    subcategory: "Services",
    price: 55000,
    images: ["https://images.unsplash.com/photo-1519699047748-de8e457a634e"],
    rating: 5.0,
    reviewCount: 15,
    inStock: true,
    stockCount: 99,
    tags: ["bridal", "luxury"],
    description: "Elegant bridal styling tailored to your wedding.",
    details: ["2.5 hours", "Consultation included", "Trial available"],
    isNew: false,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "serv-5",
    slug: "full-head-color",
    name: "Full Head Custom Color",
    category: "hair",
    subcategory: "Services",
    price: 40000,
    images: ["https://images.unsplash.com/photo-1605497746465-95394e48ef94"],
    rating: 4.7,
    reviewCount: 29,
    inStock: true,
    stockCount: 99,
    tags: ["new", "color"],
    description: "Expert color application from fashion to balayage.",
    details: ["4 hours", "Blow-dry included", "Patch test required"],
    isNew: true,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "serv-6",
    slug: "luxury-gel-pedi",
    name: "Luxury Gel Pedicure",
    category: "nails",
    subcategory: "Services",
    price: 12000,
    images: ["https://images.unsplash.com/photo-1519014816548-bf5fe059798b"],
    rating: 4.9,
    reviewCount: 110,
    inStock: true,
    stockCount: 99,
    tags: ["popular", "spa"],
    description: "Complete foot care with gel polish finish.",
    details: ["1.5 hours", "Paraffin wax included", "Callus removal"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "serv-7",
    slug: "acrylic-full-set",
    name: "Acrylic Full Set",
    category: "nails",
    subcategory: "Services",
    price: 18000,
    images: ["https://images.unsplash.com/photo-1604654894610-df490651e194"],
    rating: 4.8,
    reviewCount: 64,
    inStock: true,
    stockCount: 99,
    tags: ["acrylic", "design"],
    description: "Sculpted acrylic nails with custom art.",
    details: ["2 hours", "Multiple shapes", "Art included"],
    isNew: true,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "serv-8",
    slug: "biab-overlays",
    name: "BIAB Overlays",
    category: "nails",
    subcategory: "Services",
    price: 15000,
    images: ["https://images.unsplash.com/photo-1632345031435-8727f6897d53"],
    rating: 5.0,
    reviewCount: 38,
    inStock: true,
    stockCount: 99,
    tags: ["natural", "growth"],
    description: "Builder In A Bottle for strength on natural nails.",
    details: ["1 hour", "No chipping", "Strengthens nails"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "serv-9",
    slug: "mani-pedi-combo",
    name: "Mani-Pedi Combo",
    category: "nails",
    subcategory: "Services",
    price: 20000,
    images: ["https://images.unsplash.com/photo-1522337360788-8b13df772ec2"],
    rating: 4.9,
    reviewCount: 92,
    inStock: true,
    stockCount: 99,
    tags: ["package", "bridal"],
    description: "Full hand and foot grooming duo.",
    details: ["2.5 hours", "Dual techs", "Drink included"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "serv-10",
    slug: "intricate-nail-art",
    name: "Intricate Nail Art",
    category: "nails",
    subcategory: "Services",
    price: 5000,
    images: ["https://images.unsplash.com/photo-1607535445250-9c299c693a98"],
    rating: 5.0,
    reviewCount: 120,
    inStock: true,
    stockCount: 99,
    tags: ["art", "design"],
    description: "Hand-painted designs or Swarovski crystals.",
    details: ["30 mins", "Professional finish", "Custom designs"],
    isNew: false,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "serv-11",
    slug: "classic-lashes",
    name: "Classic Eyelash Extensions",
    category: "beauty",
    subcategory: "Services",
    price: 15000,
    images: ["https://images.unsplash.com/photo-1583001809272-139f37960a3d"],
    rating: 4.8,
    reviewCount: 55,
    inStock: true,
    stockCount: 99,
    tags: ["popular", "lashes"],
    description: "Individual lash application for natural enhancement.",
    details: ["2 hours", "Lasts 3-4 weeks", "Silk lashes"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "serv-12",
    slug: "signature-facial",
    name: "Signature Glow Facial",
    category: "beauty",
    subcategory: "Services",
    price: 25000,
    images: ["https://images.unsplash.com/photo-1570172619644-dfd03ed5d881"],
    rating: 5.0,
    reviewCount: 44,
    inStock: true,
    stockCount: 99,
    tags: ["popular", "skincare"],
    description: "Deep cleansing and specialized masking.",
    details: ["1.5 hours", "Includes extraction", "Medical grade"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "serv-13",
    slug: "brow-lamination",
    name: "Brow Lamination & Tint",
    category: "beauty",
    subcategory: "Services",
    price: 18000,
    images: ["https://images.unsplash.com/photo-1596178065887-1198b6148b2b"],
    rating: 4.7,
    reviewCount: 31,
    inStock: true,
    stockCount: 99,
    tags: ["brows", "new"],
    description: "Defined brows that stay in place.",
    details: ["1 hour", "Includes waxing", "Custom tint"],
    isNew: true,
    isBestseller: false,
    isSale: false,
  },
  {
    id: "serv-14",
    slug: "full-glam-makeup",
    name: "Full Glam Makeup",
    category: "beauty",
    subcategory: "Services",
    price: 30000,
    images: ["https://images.unsplash.com/photo-1522338140262-f46f5913618a"],
    rating: 4.9,
    reviewCount: 68,
    inStock: true,
    stockCount: 99,
    tags: ["glam", "luxury"],
    description: "Red-carpet ready makeup. Includes lashes.",
    details: ["1.5 hours", "Lashes included", "Highlight/Contour"],
    isNew: false,
    isBestseller: true,
    isSale: false,
  },
  {
    id: "serv-15",
    slug: "teeth-whitening",
    name: "Teeth Whitening (Express)",
    category: "beauty",
    subcategory: "Services",
    price: 22000,
    images: ["https://images.unsplash.com/photo-1588776814546-1ffce47267a5"],
    rating: 4.8,
    reviewCount: 19,
    inStock: true,
    stockCount: 99,
    tags: ["new", "smile"],
    description: "Brightening treatment for a lighter smile.",
    details: ["45 mins", "Pain-free", "Instant results"],
    isNew: true,
    isBestseller: false,
    isSale: false,
  },
];
